/** Port of TeXicode node_data.py — parser grammar definitions. */

// Type aliases for clarity
export type TokenType = string;
export type TokenVal = string;
export type Token = [TokenType, TokenVal];
export type NodeType = string;

// The keys for the dicts will be stringified tuples like JSON.stringify([parent_type, token_type])
// But to keep it simpler and type-safe in TS we can build nested maps or use custom keys.
// For static definition, we'll use string keys like `${parent}|${token_type},${token_val}`

export const parentDependentTypeDict: Record<string, NodeType> = {
  "cmd_sqrt|symb,[":  "opn_degr",
  "opn_degr|symb,]":  "cls_degr",

  "cmd_sbstk|symb,{":  "opn_stkln",
  "opn_stkln|symb,}":  "cls_stkln",
  "stk_lbrk|symb,}":  "cls_stkln",

  "opn_stkln|cmnd,\\": "stk_lbrk",
  "stk_lbrk|cmnd,\\": "stk_lbrk",
  "opn_stkln|cmnd,newline": "stk_lbrk",
  "stk_lbrk|cmnd,newline": "stk_lbrk",

  "cmd_bgin|symb,{":  "opn_envn",
  "cmd_end|symb,{":  "opn_envn",
  "opn_envn|symb,}":  "cls_envn",

  "cmd_text|symb,{":  "opn_text",
  "opn_text|symb,}":  "cls_text",
  "opn_text|symb, ":  "txt_leaf",

  "opn_dllr|symb,$":  "cls_dllr",
  "opn_ddlr|symb,$$": "cls_ddlr",
  "cmd_lbrk|symb,$":  "cls_dllr",
  "cmd_lbrk|symb,$$": "cls_ddlr",
};

export const typeDependentTypeDict: Record<string, NodeType> = {
  "opn_envn|symb": "txt_info",
  "opn_envn|alph": "txt_info",
  "opn_envn|numb": "txt_info",
};

export const typeDict: Record<string, NodeType> = {
  "meta,start": "opn_root", "meta,end": "cls_root",
  "meta,startline": "opn_line", "meta,endline": "cls_line",
  "symb,^": "sup_scrpt", "symb,_": "sub_scrpt",
  "symb,$": "opn_dllr",  "symb,$$": "opn_ddlr",
  "cmnd,[": "opn_brak",  "cmnd,]": "cls_brak",
  "cmnd,(": "opn_pren",  "cmnd,)": "cls_pren",
  "symb,{": "opn_brac",  "symb,}": "cls_brac",
  "symb, ": "txt_invs",

  "cmnd,left": "opn_dlim", "cmnd,right": "cls_dlim",
  "cmnd,bigl": "big_dlim", "cmnd,big": "big_dlim",
  "cmnd,bigr": "big_dlim", "cmnd,Bigl": "big_dlim",
  "cmnd,Big": "big_dlim", "cmnd,Bigr": "big_dlim",
  "cmnd,biggl": "big_dlim", "cmnd,bigg": "big_dlim",
  "cmnd,biggr": "big_dlim", "cmnd,Biggl": "big_dlim",
  "cmnd,Bigg": "big_dlim", "cmnd,Biggr": "big_dlim",

  "cmnd,sqrt": "cmd_sqrt",

  "cmnd,frac": "cmd_frac", "cmnd,tfrac": "cmd_frac",
  "cmnd,dfrac": "cmd_frac", "cmnd,cfrac": "cmd_frac",

  "cmnd,sum": "ctr_base", "cmnd,prod": "ctr_base",
  "cmnd,lim": "ctr_base",

  "cmnd,binom": "cmd_binom", "cmnd,dbinom": "cmd_binom",

  "cmnd,limits": "cmd_lmts", "cmnd,acute": "cmd_acnt",
  "cmnd,bar": "cmd_acnt", "cmnd,breve": "cmd_acnt",
  "cmnd,check": "cmd_acnt", "cmnd,ddot": "cmd_acnt",
  "cmnd,dot": "cmd_acnt", "cmnd,grave": "cmd_acnt",
  "cmnd,hat": "cmd_acnt", "cmnd,mathring": "cmd_acnt",
  "cmnd,tilde": "cmd_acnt", "cmnd,vec": "cmd_acnt",
  "cmnd,widehat": "cmd_acnt", "cmnd,widetilde": "cmd_acnt",

  "cmnd,mathrm": "cmd_font", "cmnd,mathbf": "cmd_font",
  "cmnd,mathsf": "cmd_font", "cmnd,mathtt": "cmd_font",
  "cmnd,mathit": "cmd_font", "cmnd,mathnormal": "cmd_font",
  "cmnd,mathcal": "cmd_font", "cmnd,mathfrak": "cmd_font",
  "cmnd,mathbb": "cmd_font", "cmnd,mathscr": "cmd_font",

  "cmnd,text": "cmd_text",

  "cmnd,substack": "cmd_sbstk",
  "cmnd,\\": "cmd_lbrk", "cmnd,newline": "cmd_lbrk",
  "cmnd,begin": "cmd_bgin", "cmnd,end": "cmd_end",

  "cmnd,textstyle": "cmd_styl",
  "cmnd,displaystyle": "cmd_styl",
  "cmnd,scriptstyle": "cmd_styl",
  "cmnd,scriptscriptstyle": "cmd_styl",
};

export const selfDependentTypeDict: Record<string, NodeType> = {
  "symb": "txt_leaf",
  "alph": "txt_leaf",
  "numb": "txt_leaf",
  "cmnd": "cmd_leaf",
};

// node_info tuple structure in Python:
// (
//   (only/only_not: boolean, popable_by: string[]),
//   (add_amount: number),
//   (can_add_to_nodes_tree: boolean, err if/if_not: boolean, under: string[]),
//   (can_be_children: boolean, can_break_parent: boolean, can_double_pop: boolean),
//   (token_depented_render: boolean, rendering_function: string | null)
// )
export type TypeInfo = [
  [boolean, string[]],
  [number],
  [boolean, boolean, string[]],
  [boolean, boolean, boolean],
  [boolean, string | null]
];

export const typeInfoDict: Record<string, TypeInfo> = {
  "opn_root":  [[true, ["cls_root"]],
                [1],
                [true, true, []],
                [false, false, false],
                [false, "render_root"]],
  "opn_brac":  [[true, ["cls_brac"]],
                [1],
                [true, true, []],
                [true, false, false],
                [false, "render_concat"]],
  "opn_degr":  [[true, ["cls_degr"]],
                [1],
                [true, false, ["cmd_sqrt"]],
                [true, false, false],
                [false, "render_concat"]],
  "opn_dlim":  [[true, ["cls_dlim"]],
                [1],
                [true, true, []],
                [true, false, false],
                [false, "render_open_delimiter"]],
  "cmd_sqrt":  [[false, ["opn_degr"]],
                [1],
                [true, true, []],
                [true, false, false],
                [false, "render_square_root"]],
  "cmd_frac":  [[false, []],
                [2],
                [true, true, []],
                [true, false, false],
                [false, "render_fraction"]],
  "cmd_binom": [[false, []],
                [2],
                [true, true, []],
                [true, false, false],
                [false, "render_binomial"]],
  "big_dlim":  [[false, []],
                [1],
                [true, true, []],
                [true, false, false],
                [true, "render_big_delimiter"]],
  "sup_scrpt": [[false, []],
                [1],
                [true, true, []],
                [true, false, false],
                [false, "render_sup_script"]],
  "sub_scrpt": [[false, []],
                [1],
                [true, true, []],
                [true, false, false],
                [false, "render_sub_script"]],
  "top_scrpt": [[false, []],
                [1],
                [true, true, []],
                [true, false, false],
                [false, "render_top_script"]],
  "btm_scrpt": [[false, []],
                [1],
                [true, true, []],
                [true, false, false],
                [false, "render_bottom_script"]],
  "cls_dlim":  [[false, []],
                [1],
                [true, true, []],
                [true, false, false],
                [false, "render_close_delimiter"]],
  "cmd_acnt":  [[false, []],
                [1],
                [true, true, []],
                [true, false, false],
                [true, "render_accents"]],
  "cmd_font":  [[false, []],
                [1],
                [true, true, []],
                [true, false, false],
                [true, "render_font"]],
  "cmd_lmts":  [[true, []],
                [0],
                [true, true, []],
                [true, false, false],
                [false, null]],
  "ctr_base":  [[true, []],
                [0],
                [true, true, []],
                [true, false, false],
                [true, "render_leaf"]],
  "txt_leaf":  [[true, []],
                [0],
                [true, true, []],
                [true, false, false],
                [true, "render_leaf"]],
  "txt_info":  [[true, []],
                [0],
                [true, true, []],
                [true, false, false],
                [true, "render_text_info"]],
  "txt_invs":  [[true, []],
                [0],
                [false, true, []],
                [false, false, false],
                [false, null]],
  "cmd_leaf":  [[true, []],
                [0],
                [true, true, []],
                [true, false, false],
                [true, "render_leaf"]],
  "cmd_styl":  [[true, []],
                [0],
                [false, true, []],
                [false, false, false],
                [false, null]],
  "cls_root":  [[true, []],
                [0],
                [false, false, ["opn_root"]],
                [false, false, false],
                [false, null]],
  "cls_brac":  [[true, []],
                [0],
                [false, false, ["opn_brac"]],
                [false, false, false],
                [false, null]],
  "cls_degr":  [[true, []],
                [0],
                [false, false, ["opn_degr"]],
                [false, false, false],
                [false, null]],
  "cls_line":  [[true, []],
                [0],
                [false, false, ["opn_line", "cmd_lbrk"]],
                [false, false, false],
                [false, null]],
  "cls_brak":  [[true, []],
                [0],
                [false, false, ["opn_brak", "cmd_lbrk"]],
                [false, false, false],
                [false, null]],
  "cls_pren":  [[true, []],
                [0],
                [false, false, ["opn_pren", "cmd_lbrk"]],
                [false, false, false],
                [false, null]],
  "cls_dllr":  [[true, []],
                [0],
                [false, false, ["opn_dllr", "cmd_lbrk"]],
                [false, false, false],
                [false, null]],
  "cls_ddlr":  [[true, []],
                [0],
                [false, false, ["opn_ddlr", "cmd_lbrk"]],
                [false, true, false],
                [false, null]],
  "cmd_end":   [[false, []],
                [1],
                [true, false, ["cmd_bgin", "cmd_lbrk"]],
                [false, true, false],
                [false, "render_end"]],
  "cls_stkln": [[true, []],
                [0],
                [false, false, ["opn_stkln", "stk_lbrk"]],
                [false, true, true],
                [false, null]],
  "cls_envn":  [[true, []],
                [0],
                [false, false, ["opn_envn"]],
                [false, false, false],
                [false, null]],
  "cls_text":  [[true, []],
                [0],
                [false, false, ["opn_text"]],
                [false, false, false],
                [false, null]],
  "opn_line":  [[true, ["cls_line", "cmd_lbrk"]],
                [1],
                [true, false, ["opn_root"]],
                [true, false, false],
                [false, "render_concat_line_no_align_amp"]],
  "opn_brak":  [[true, ["cls_brak", "cmd_lbrk"]],
                [1],
                [true, false, ["opn_root"]],
                [true, false, false],
                [false, "render_concat_line_no_align_amp"]],
  "opn_pren":  [[true, ["cls_pren", "cmd_lbrk"]],
                [1],
                [true, false, ["opn_root"]],
                [true, false, false],
                [false, "render_concat_line_no_align_amp"]],
  "opn_dllr":  [[true, ["cls_dllr", "cmd_lbrk"]],
                [1],
                [true, false, ["opn_root"]],
                [true, false, false],
                [false, "render_concat_line_no_align_amp"]],
  "opn_ddlr":  [[true, ["cls_ddlr", "cmd_lbrk"]],
                [1],
                [true, false, ["opn_root"]],
                [true, false, false],
                [false, "render_concat_line_no_align_amp"]],
  "cmd_bgin":  [[true, ["cmd_end"]],
                [1],
                [true, true, []],
                [true, false, false],
                [false, "render_begin"]],
  "stk_lbrk":  [[true, ["cls_stkln", "stk_lbrk"]],
                [1],
                [true, false, ["opn_stkln", "stk_lbrk"]],
                [true, true, false],
                [false, "render_concat_line_no_align_amp"]],
  "opn_stkln": [[true, ["cls_stkln", "stk_lbrk"]],
                [1],
                [true, false, ["cmd_sbstk"]],
                [true, false, false],
                [false, "render_concat_line_no_align_amp"]],
  "opn_envn":  [[true, ["cls_envn"]],
                [1],
                [true, false, ["cmd_bgin", "cmd_end"]],
                [true, false, false],
                [false, "render_concat"]],
  "opn_text":  [[true, ["cls_text"]],
                [1],
                [true, false, ["cmd_text"]],
                [true, false, false],
                [false, "render_concat"]],
  "cmd_text":  [[false, []],
                [1],
                [true, true, []],
                [true, false, false],
                [true, "render_font"]],
  "cmd_sbstk": [[true, ["cls_stkln"]],
                [1],
                [true, true, []],
                [true, false, false],
                [false, "render_substack"]],
  "cmd_lbrk":  [[true, ["cmd_lbrk", "cls_line", "cls_brak", "cls_pren", "cls_dllr", "cls_ddlr", "cmd_end"]],
                [1],
                [true, false, ["cmd_lbrk", "opn_line", "opn_brak", "opn_pren", "opn_dllr", "opn_ddlr", "cmd_bgin"]],
                [true, true, false],
                [false, "render_concat_line_align_amp"]],
};
